cargo-features = ["strip"]

[workspace]
members = [
    "code",
    "load",
    "shim",
]

default-members = [
    "code",
    "load"
]

[profile.dev]
panic = "abort"

[profile.release]
incremental = false
codegen-units = 1
opt-level = "s"
panic = "abort"
strip = true
lto = true
