cargo-features = ["per-package-target"]

[package]
name = "shim"
version = "0.1.0"
edition = "2018"
forced-target = "x86_64-unknown-linux-gnu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
